### ISSUE TITLE
About the strange unit conversion used in this tutorial.

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/Advanced_Jobflow_Tutorial#15]
Hi there,

I've seen [the following unit conversion](https://jageo.github.io/Advanced_Jobflow_Tutorial/tutorial.html#plotting-and-evaluating-the-equation-of-state) used in this tutorial:

```python
from ase.units import kJ
from ase.eos import EquationOfState

eos = EquationOfState(volumes, energies)
v0, e0, B = eos.fit()
print(B, 'eV Angstrom**(-3)')
print(B / kJ * 1.0e24, 'GPa')
eos.plot('outputs/Ag-eos.png')
```
But, according to my understanding, the conversion of 'eV Angstrom**(-3)' to 'GPa' is like the following:

```python
In [2]: def ev_per_angstrom3_to_gpa(B):
   ...:     # 1 eV = 1.60218e-19 J
   ...:     # 1 Å³ = 1e-30 m³
   ...:     # 1 GPa = 1e9 Pa = 1e9 J/m³
   ...:     return B * 1.60218e-19 / 1e-30 / 1e9
   ...: 

In [3]: ev_per_angstrom3_to_gpa(1)
Out[3]: 160.21799999999996
```
What I mean is that the above conversion is not related to the `/kJ * 1.0e24` part in the original code snippet. Therefore, why use the conversion factor of `/kJ * 1.0e24`, which makes me feel very confused. Any hints/comments will be appreciated.

See https://github.com/hgrecco/pint/issues/2038 for the related discussion.

Regards,
Zhao

**Comment by JaGeo** [comment]
@hongyi-zhao First of all, this is a tutorial about the automation and not the equations of state.
Second of all, this tutorial is based on the ase tutorial:
https://wiki-fysik-dtu-dk.translate.goog/ase/tutorials/eos/eos.html?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=de&_x_tr_pto=sc#eos

**Comment by JaGeo** [comment]
@hongyi-zhao see here in the ase documentation:
https://wiki-fysik-dtu-dk.translate.goog/ase/ase/eos.html?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=de&_x_tr_pto=sc

**Comment by JaGeo** [comment]
(sent you the translated version by accident but I guess you can switch it Off)

**Comment by hongyi-zhao** [comment]
The tests below show that the conversion method I used is indeed equivalent to [the one provided by ASE](https://gitlab.com/ase/ase/-/blob/master/ase/units.py?ref_type=heads#L175):

```python
# Find the relevant code snippets that appear in the ase repository:
# werner@x13dai-t:~$ cd "/home/werner/Public/repo/gitlab.com/ase/ase.git" && ug -A10 -B10 -i 1.0e24
In [14]: from ase.units import kJ, _e
    ...: 
    ...: # Convert eV/Å³ to GPa, the ASE method:
    ...: result1 = 1/kJ * 1.0e24
    ...: print(f"Conversion factor eV/Å³ to GPa (ASE method) = {result1}")
    ...: 
    ...: # Convert eV/Å³ to GPa, the manual method:
    ...: result2 = _e / 1e-30 / 1e9
    ...: print(f"Conversion factor eV/Å³ to GPa (manual method) = {result2}")
    ...: 
    ...: # Display the ASE definition of kJ (in eV)
    ...: print(f"1 kJ in eV (ASE definition) = {kJ}")
    ...: 
    ...: # Manually calculate the number of eV in 1 kJ
    ...: manual_calculation = 1000/_e
    ...: print(f"1 kJ in eV (manual calculation) = {manual_calculation}")
    ...: 
    ...: # Compare ASE's kJ definition with the manual calculation
    ...: difference = abs(kJ - manual_calculation)
    ...: print(f"Difference between ASE definition and manual calculation: {difference}")
    ...: 
    ...: # Display the electron charge defined in ASE
    ...: print(f"Electron charge (from ASE) = {_e}")
Conversion factor eV/Å³ to GPa (ASE method) = 160.21766208
Conversion factor eV/Å³ to GPa (manual method) = 160.21766208
1 kJ in eV (ASE definition) = 6.241509125883258e+21
1 kJ in eV (manual calculation) = 6.241509125883258e+21
Difference between ASE definition and manual calculation: 0.0
Electron charge (from ASE) = 1.6021766208e-19
```
