### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by arosen93** [JaGeo/Advanced_Jobflow_Tutorial#3]
Occasionally, `M̀aker` is written instead of `Maker`. Just a head's up! :)

**Comment by JaGeo** [comment]
Thank you 🥴. I will correct it next week. I think it's a problem with my editor.

**Comment by arosen93** [comment]
Haha it happens! Super minor. I had an issue last week where random letters on my keyboard were randomly getting accented and it took me forever to figure out why........

**Comment by JaGeo** [comment]
I think I fixed it but I will look at it carefully next week again. You might spot additional problems.

**Comment by JaGeo** [comment]
@arosen93 I have updated the readme 😇

**Comment by arosen93** [comment]
Ha! Thanks :D Although I don't know that this really counts as a contribution! Hopefully I can make up for it and contribute more in the future though :)
